FROM alpine:3.20

RUN apk add --no-cache gcc musl-dev mariadb-connector-c-dev gdb gdbserver

WORKDIR /app
COPY include/ include/
COPY src/ src/

ARG DB_HOST=db
RUN sed -i "s/#define DB_HOST \"localhost\"/#define DB_HOST \"${DB_HOST}\"/" include/config.h

RUN mkdir -p output && gcc src/main.c src/conexao.c \
    -g \
    -I /usr/include/mysql \
    -I include \
    -L /usr/lib \
    -lmariadb \
    -o output/cmysql

EXPOSE 2345
CMD ["gdbserver", "--once", "0.0.0.0:2345", "./output/cmysql"]
